const { withPodfile } = require('@expo/config-plugins');

const MARKER = '$RNFirebaseDisableSPM';

// react-native-firebase's pods can resolve some of their Firebase transitive deps (GoogleUtilities,
// GTMSessionFetcher, etc.) via Swift Package Manager under Xcode 15+, since firebase-ios-sdk ships
// SPM package definitions alongside its podspecs. Those SPM products are static libraries, and this
// project's Podfile doesn't call `use_frameworks!` (default static linkage), so `pod install` fails
// with:
//   [react-native-firebase] SPM + static linkage is not supported (target(s): Pods-ShoppersDeals).
// react-native-firebase's own suggested fix (see the pod install error) is to opt out of the SPM
// resolution path entirely by setting $RNFirebaseDisableSPM = true before any target block, which
// forces pure CocoaPods dependency resolution instead — no linkage changes needed elsewhere.
//
// `ios/` is regenerated by `expo prebuild`, so this must be injected via a config plugin rather
// than hand-edited in ios/Podfile.
function withRNFirebaseDisableSPM(config) {
  return withPodfile(config, (config) => {
    const contents = config.modResults.contents;

    if (contents.includes(MARKER)) {
      return config;
    }

    // Insert right before the first `target` block, after any leading `require`s.
    const marker = /(\ntarget\s+['"])/;
    if (!marker.test(contents)) {
      throw new Error(
        '[withRNFirebaseDisableSPM] Could not find a `target` block in ios/Podfile to anchor the fix.'
      );
    }

    config.modResults.contents = contents.replace(
      marker,
      `\n${MARKER} = true\n$1`
    );

    return config;
  });
}

module.exports = withRNFirebaseDisableSPM;
