const { withPodfile, withPodfileProperties } = require('@expo/config-plugins');

const PHASE_MARKER = 'Embed ExpoModulesJSI Framework';

// Workaround for an expo-modules-jsi packaging bug: ExpoModulesJSI.framework
// is built by a CocoaPods PBXAggregateTarget script phase rather than a
// normal vendored xcframework, so CocoaPods never adds it to the app's
// "Embed Pods Frameworks" script the way it does for ExpoFont/ExpoModulesCore/
// etc. Without this, the app installs on device/simulator but crashes
// instantly on launch with:
//   dyld: Library not loaded: @rpath/ExpoModulesJSI.framework/ExpoModulesJSI
//
// `ios/` is regenerated by `expo prebuild`, so this must be injected via a
// config plugin rather than hand-edited in ios/Podfile.
//
// TODO: drop this plugin once upstream expo-modules-jsi embeds the framework
// itself (tracked alongside patches/expo-modules-jsi+*.patch).
const POST_INSTALL_SNIPPET = `
    # Workaround: ExpoModulesJSI.framework is built by a CocoaPods
    # PBXAggregateTarget script phase rather than a normal vendored
    # xcframework, so CocoaPods never adds it to the app's "Embed Pods
    # Frameworks" script (unlike ExpoFont/ExpoModulesCore/etc, which are
    # embedded fine). Without this, the app installs but crashes instantly
    # on launch with:
    #   dyld: Library not loaded: @rpath/ExpoModulesJSI.framework/ExpoModulesJSI
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_targets.each do |user_target|
        phase_name = '${PHASE_MARKER}'
        next if user_target.shell_script_build_phases.any? { |p| p.name == phase_name }
        phase = user_target.new_shell_script_build_phase(phase_name)
        phase.shell_script = <<~SH
          set -e
          SRC="\${PODS_CONFIGURATION_BUILD_DIR}/XCFrameworkIntermediates/ExpoModulesJSI/ExpoModulesJSI.framework"
          if [ -d "$SRC" ] && [ -n "\${FRAMEWORKS_FOLDER_PATH:-}" ]; then
            DEST="\${TARGET_BUILD_DIR}/\${FRAMEWORKS_FOLDER_PATH}"
            mkdir -p "$DEST"
            rsync -a --delete "$SRC" "$DEST/"
            if [ -n "\${EXPANDED_CODE_SIGN_IDENTITY:-}" ] && [ "\${CODE_SIGNING_REQUIRED:-}" != "NO" ] && [ "\${CODE_SIGNING_ALLOWED:-}" != "NO" ]; then
              /usr/bin/codesign --force --sign "\${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements "$DEST/ExpoModulesJSI.framework"
            fi
          fi
        SH
        user_target.build_phases.move(phase, -1)
      end
    end
`;

// Separately: the "precompiled modules" pipeline (EXPO_USE_PRECOMPILED_MODULES,
// on by default) downloads prebuilt xcframeworks for ExpoModulesCore, ExpoFont,
// ExpoFileSystem, ExpoContacts and ExpoModulesWorklets. In this project those
// prebuilt binaries are out of sync with the locally patched ExpoModulesCore
// source (see patches/expo-modules-core+*.patch), which causes a launch-time
// crash distinct from the one above:
//   dyld: Symbol not found: _$s15ExpoModulesCore10BaseModuleC11willDestroyyyFTj
// Forcing all Expo modules to build from source together keeps them mutually
// ABI-consistent. This costs extra build time — remove once the precompiled
// artifacts are rebuilt against the patched ExpoModulesCore source.
function withExpoModulesBuildFromSource(config) {
  return withPodfileProperties(config, (config) => {
    config.modResults['EXPO_USE_PRECOMPILED_MODULES'] = 'false';
    return config;
  });
}

function withExpoModulesJSIEmbedFix(config) {
  config = withPodfile(config, (config) => {
    const contents = config.modResults.contents;

    if (contents.includes(PHASE_MARKER)) {
      return config;
    }

    // Insert right after the react_native_post_install(...) call, inside the
    // `post_install do |installer| ... end` block.
    const marker = /(react_native_post_install\(\s*[\s\S]*?\)\s*\n)/;
    if (!marker.test(contents)) {
      throw new Error(
        '[withExpoModulesJSIEmbedFix] Could not find react_native_post_install(...) call in ios/Podfile to anchor the fix.'
      );
    }

    config.modResults.contents = contents.replace(
      marker,
      `$1${POST_INSTALL_SNIPPET}`
    );

    return config;
  });

  return withExpoModulesBuildFromSource(config);
}

module.exports = withExpoModulesJSIEmbedFix;
